import Head from 'next/head'
import styles from '../../styles/Home.module.css'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
			About
        </h1>

        <p className={styles.description}>
        	This is an app written in Nextjs
        </p>
      </main>
    </div>
  )
}

