name: ESLint CI
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "*"
      - "!main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: pnpm install
    - name: Run ESLint
      run: eslint --ext .astro src/