name: Lighthouse CI (Development)
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "*"
      - "!main"
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          path: .
          node-version: 'lts/*'
          package-manager: pnpm@latest
      - name: Install Dependencies
        run: pnpm install
      - name: Run Lighthouse test
        run: npx lhci autorun --config lighthouserc-dev.cjs

