name: Lighthouse CI (Production)
on:
  push:
    branches:
      - "main"
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install Dependencies
        run: npm install && npm install -g @lhci/cli@0.11.x
      - name: Run Lighthouse test
        run: lhci autorun --config lighthouserc-prod.cjs

